version: "3"

services:
  web:
    image: tadoku/maintenance:latest
    container_name: tadoku-web-maintenance
    network_mode: bridge
    restart: always
    expose:
      - 80
    environment:
      VIRTUAL_HOST: tadoku.app
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: tadoku.app
      LETSENCRYPT_EMAIL: hello@tadoku.app

